name: Test report upload
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  GithubPageTests:
    name: "Github tests"
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    env:
      TESTGROUP: Github test
      BASEURL: https://playwright.dev/docs/accessibility-testing # Playwright tests use this for baseURL
    environment:
      name: Github Test
      url: https://josh-keegan.github.io/Test-Results/
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Run ${{ env.TESTGROUP }} Tests
        continue-on-error: true
        working-directory: ${{ env.TESTGROUP }}
        run: |
          npx playwright install
           npx playwright test
      - name: Upload HTML report as artifact. To troubleshoot failures, extract .zip and double-click index.html.
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ env.TESTGROUP }}
          path: |
            test-results/trace.zip
